# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-08 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='\u6807\u9898')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='link')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='\u5185\u5bb9')),
                ('time', models.DateField(db_index=True, null=True, verbose_name='\u65e5\u671f')),
                ('status', models.IntegerField(null=True, verbose_name='\u72b6\u6001')),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
