# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-09 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_trump'),
    ]

    operations = [
        migrations.AddField(
            model_name='trump',
            name='exttime',
            field=models.DateField(db_index=True, null=True, verbose_name='\u65e5\u671f'),
        ),
    ]
