# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-11 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_trump_exttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, null=True, verbose_name='内容')),
                ('tag', models.CharField(max_length=100, null=True, verbose_name='标记')),
                ('time', models.DateTimeField(db_index=True, null=True, verbose_name='日期')),
                ('exttime', models.DateField(db_index=True, null=True, verbose_name='日期')),
                ('status', models.IntegerField(null=True, verbose_name='状态')),
            ],
            options={
                'db_table': 'jten',
            },
        ),
    ]
